/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.polsl.polynomialderivative.view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.TableColumn;
import pl.polsl.polynomialderivative.controller.Controller;
import pl.polsl.polynomialderivative.exceptions.NegatvieNumber;
import pl.polsl.polynomialderivative.exceptions.NotEnoughDataInArray;
import pl.polsl.polynomialderivative.model.Polynomial;

/**
 * Class used to make GUI
 *
 * @author Bartosz Matusik
 */
public class ViewGUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewGUI
     */
    public ViewGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculateBtn = new javax.swing.JButton();
        degreeTxt = new javax.swing.JTextField();
        degreeLbl = new javax.swing.JLabel();
        factorsLbl = new javax.swing.JLabel();
        derivativeLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        resultTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        factorsTable = new javax.swing.JTable();
        errorLbl = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Polynomial Derivative");

        calculateBtn.setText("Calculate");

        degreeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeTxtActionPerformed(evt);
            }
        });

        degreeLbl.setText("Degree");

        factorsLbl.setText("Factors");

        derivativeLbl.setText("Derivative");

        resultTxt.setEditable(false);
        resultTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTxtActionPerformed(evt);
            }
        });

        factorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        factorsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        factorsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        factorsTable.setSelectionBackground(new java.awt.Color(75, 120, 215));
        factorsTable.setShowGrid(true);
        jScrollPane3.setViewportView(factorsTable);

        errorLbl.setForeground(new java.awt.Color(255, 0, 0));

        acceptBtn.setText("Accept degree");
        acceptBtn.setToolTipText("Accept positive integer of degree");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degreeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(resultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(109, 109, 109))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(derivativeLbl)
                                    .addComponent(factorsLbl))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(degreeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculateBtn)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(degreeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(degreeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acceptBtn)))
                .addGap(16, 16, 16)
                .addComponent(factorsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(derivativeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(resultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculateBtn)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void degreeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeTxtActionPerformed

    }//GEN-LAST:event_degreeTxtActionPerformed

    private void resultTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTxtActionPerformed

    }//GEN-LAST:event_resultTxtActionPerformed

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        errorLbl.setText("");
        try {
            if (Integer.parseInt(degreeTxt.getText()) < 0) {
                throw new NegatvieNumber("");
            }
            int size = Integer.parseInt(degreeTxt.getText()) + 1;
            Object[][] rows = new Object[1][size];
            for (int i = 0; i < size; i++) {
                rows[0][i] = 0;
            }
            String[] titles = new String[size];
            int counter = size - 1;
            for (int i = 0; i < size; i++) {
                titles[i] = "x^" + Integer.toString(counter--);
            }
            factorsTable.setModel(new javax.swing.table.DefaultTableModel(
                    rows,
                    titles
            ) {
                @Override
                public Class getColumnClass(int columnIndex) {
                    return java.lang.Double.class;
                }
            });
        } catch (java.lang.NumberFormatException e) {
            errorLbl.setText("Enter integer!");
        } catch (NegatvieNumber e) {
            errorLbl.setText("Enter POSITIVE integer!");
        }
    }//GEN-LAST:event_acceptBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel degreeLbl;
    private javax.swing.JTextField degreeTxt;
    private javax.swing.JLabel derivativeLbl;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JLabel factorsLbl;
    private javax.swing.JTable factorsTable;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField resultTxt;
    // End of variables declaration//GEN-END:variables

    public int getDegree() {
        int degree = 0;
        try {
            degree = Integer.parseInt(degreeTxt.getText());

        } catch (java.lang.NumberFormatException e) {
            errorLbl.setText("Enter integer!");
        }
        return degree;
    }

    public ArrayList<Double> getFactors() {
        ArrayList<Double> factors = new ArrayList<>();
        try {
            for (int i = 0; i <= getDegree(); i++) {
                factors.add(Double.parseDouble((factorsTable.getModel().getValueAt(0, i)).toString()));
            }
        } catch (java.lang.ArrayIndexOutOfBoundsException e) {
            errorLbl.setText("Accept degree first to enter factors!");
        }
        return factors;
    }

    public void setResultTxt(String result) {
        resultTxt.setText(result);
    }

    private void msgbox(String dont_touch_that) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void addCalculateListener(ActionListener mal) {
        calculateBtn.addActionListener(mal);
    }

}
